name: 'Legacy'
description: 'Create issue for legacy patterns'
author: 'Torstein Bjørnstad'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
runs:
  using: 'node12'
  main: 'dist/index.js'
